const data = {
  roles: [
    // All engineering roles
    "Software Engineer",
    "Data Scientist",
    "Mobile Engineer",
    "DevOps Engineer",
    "Product Engineer",
    "AI/ML Engineer",
  ],
  companies: "Faang, startups, India, EU and US based",
  location:
    "SF, NYC, CA, NY, London, Paris, Berlin, Amsterdam, Munich, Zurich, Vienna, Zurich, Munich, Berlin, Paris, London, NYC, SF, CA, NY, India",
  description: "We are looking for a Software Engineer to join our team.",
  skills: [
    "Typescript",
    "JavaScript",
    "React",
    "Node.js",
    "Express",
    "Fastify",
    "MongoDB",
    "Supabase",
    "Vercel",
    "Netfify",
    "Tailwind CSS",
    "Shadcn UI",
    "Next.js",
    "Python",
    "Java",
    "C++",
    "C#",
    "C",
    "Go",
    "Rust",
    "Laravel PHP",
    "Ruby on Rails",
    "Flutter",
    "React Native",
    "Swift",
    "Kotlin",
    "Dart",
    "Flask",
    // Observability & Monitoring
    "Grafana",
    "Prometheus",
    "New Relic",
    "Datadog",
    // AI/ML
    "TensorFlow",
    "PyTorch",
    "Keras",
    "OpenAI",
    "LangChain",
    // Cloud & DevOps
    "Kubernetes",
    "Docker",
    "Terraform",
    "AWS",
    "GCP",
    "Azure",
    // Databases
    "PostgreSQL",
    "Redis",
    "Elasticsearch",
    "Cassandra",
    "Neo4j",
    // Message Queues
    "Apache Kafka",
    "RabbitMQ",
    // Analytics
    "Snowflake",
    "dbt",
    "Looker",
    "Tableau",

    // Web Technologies
    "TypeScript",
    "JavaScript",
    "Node.js",
    "Deno",
    "Bun",
    "Supabase",
    "Vercel",
    "Netlify",
    "Cloudflare",
    "Prisma",
    "tRPC",
    "GraphQL",
    "REST",
    "WebSockets",
    "WebAssembly",
    "Vite",
    "Webpack",
    "Rollup",
    "esbuild",
    "Turborepo",

    // Programming Languages
    "Rust",
    "Zig",
    "Go",
    "Elixir",
    "Haskell",
    "OCaml",
    "Nim",
    "Crystal",
    "V",
    "Carbon",
    "Odin",
    "Vale",
  ],
};
